### PR TITLE
Auth UI

### PR DESCRIPTION
**Pull request by Sky-De**
### Fixes issue #118
now auth pages UI is improved and is more aligned with material design, also fully responsive

### Screenshots

<div>
<h2>Before</h2>

</div>

<div>
<h2>After</h2>

</div>

### Consideration
code related to this PR is in the second commit "Auth pages UI updated"

### CODE REVIEW

**Comment by Sky-De** [comment]
@techy1999 please check this also

**Review by techy1999 — COMMENTED** [review]
UI look good. But we need to discuss

**Review by techy1999 — DISMISSED** [review]

**Comment by Sky-De** [comment]
> UI look good. But we need to discuss

Sure ,why not, what's the problem?
Also i got notification about app refactor PR the other night, but now i can't find that comment, i guess it was about routing system
Inform me about that
Thanks

**Comment by techy1999** [comment]
@Sky-De  When we can discuss and close this issue?

**Comment by Sky-De** [comment]
> @Sky-De When we can discuss and close this issue?

@techy1999 i was looking forward for your response, where you wanna discuss it? I'm free these days, let me know about time and platform

**Comment by techy1999** [comment]
@Sky-De Lets meet today at 10 PM IST on google meet 
Link - PR Discussion
Tuesday, May 14 · 10:00 – 11:00pm
Time zone: Asia/Kolkata
Google Meet joining info
Video call link: https://meet.google.com/dfx-qsaa-biz

**Comment by Sky-De** [comment]
> @Sky-De Lets meet today at 10 PM IST on google meet Link - PR Discussion Tuesday, May 14 · 10:00 – 11:00pm Time zone: Asia/Kolkata Google Meet joining info Video call link: https://meet.google.com/dfx-qsaa-biz

@techy1999 i just got your message, are you available now?

**Review by techy1999 — APPROVED** [review]
I am approving it. I have added project collaborator as well.
Do you have access to merge after getting approval. Let me know please?

**Comment by Sky-De** [comment]
> I am approving it. I have added you as project collaborator . You got some invite to be project collaborator Please accepts. Do you have access to merge after getting approval. Let me know please @Sky-De ?

@techy1999 I accepted that, thanks, for this PR I had to rewrite the git history to remove commit related to appRefactore, 
please check and merge this PR, if there is any other problem let me know

**Comment by techy1999** [comment]
> > I am approving it. I have added you as project collaborator . You got some invite to be project collaborator Please accepts. Do you have access to merge after getting approval. Let me know please @Sky-De ?
> 
> @techy1999 I accepted that thanks, for this PR I had to rewrite the git history to remove a commit related to appRefactore, although I have access to merging this please check and merge this PR, please check and merge this PR, if there is any other problem let me know

@Sky-De  Ok, I am merging it for now. But from next time after approval you can merge it

**Comment by Sky-De** [comment]
@techy1999 Hi, may I ask you a favor? I'd appreciate it if you could take a look at my [Portfolio ](https://skyde-portfolio.netlify.app/)and other projects. Please let me know what you think about them, and if you like them, please give them a STAR. All public projects can be found in the PROJECTS section of my portfolio. Within that section, you can find live demo links as well as repository links related to each project.And if you like my project please mention other colleagues of these projects here to check my [Portfolio ](https://skyde-portfolio.netlify.app/), thanks thanks

**Pull request merged**
